import os
import json
from datetime import datetime

from agno.knowledge.knowledge import Knowledge
from agno.knowledge.embedder.aws_bedrock import AwsBedrockEmbedder
from agno.vectordb.pgvector import PgVector

def get_knowledge_base():
    """Initializes and returns the Knowledge Base connected to Supabase PgVector."""
    db_url = os.environ.get("SUPABASE_DB_URL")
    
    if not db_url:
        print("Warning: SUPABASE_DB_URL not configured. Embeddings will not be saved.")
        return None

    # Use a dedicated boto3 session with the region from env,
    # without destructively modifying global AWS credential env vars.
    import boto3
    boto_session = boto3.Session(region_name=os.environ.get("AWS_REGION", "us-east-1"))
    embedder = AwsBedrockEmbedder(
        id="amazon.nova-multimodal-embed-v1:0",
        session=boto_session,
    )

    vector_db = PgVector(
        table_name="user_knowledge",
        db_url=db_url,
        embedder=embedder,
    )

    return Knowledge(
        name="User Document and SaaS Knowledge Base",
        description="A database of research papers and SaaS strategies generated by users.",
        vector_db=vector_db,
    )


def index_paper_session(user_id: str, paper_arxiv_id: str, paper_title: str, abstract: str, agent_analysis_dict: dict):
    """
    Takes the parsed SaaS agent results and the raw paper abstract and stores them 
    in the Supabase PgVector database under the specific user's namespace.
    """
    kb = get_knowledge_base()
    if not kb:
        return

    print(f"Indexing session for User {user_id} | Paper: {paper_arxiv_id}...")

    # Document 1: The Raw Abstract 
    abstract_content = f"Title: {paper_title}\nArXiv ID: {paper_arxiv_id}\nAbstract:\n{abstract}"
    kb.insert(
        text_content=abstract_content,
        metadata={
            "user_id": user_id,
            "arxiv_id": paper_arxiv_id,
            "doc_type": "paper_abstract",
            "indexed_at": datetime.utcnow().isoformat()
        }
    )

    # Document 2: The Agent Analysis
    analysis_content = f"SaaS Strategy derived from {paper_title}:\n\n"
    
    # Handle paperAnalysis format from the analyst
    paper_analysis = agent_analysis_dict.get("paperAnalysis", {})
    if paper_analysis:
        analysis_content += f"Core Breakthrough: {paper_analysis.get('coreBreakthrough', 'N/A')}\n"
        analysis_content += f"Summary: {paper_analysis.get('summary', 'N/A')}\n"
        innovations = paper_analysis.get('keyInnovations', [])
        if innovations:
            analysis_content += f"Key Innovations: {', '.join(innovations)}\n"

    # Handle opportunities format from the architect
    opportunities = agent_analysis_dict.get("opportunities", [])
    if isinstance(opportunities, list):
        for opp in opportunities[:5]:
            if isinstance(opp, dict):
                analysis_content += f"\nOpportunity: {opp.get('name', 'N/A')}\n"
                analysis_content += f"  Type: {opp.get('type', 'N/A')}\n"
                analysis_content += f"  Value: {opp.get('coreValue', opp.get('oneLiner', 'N/A'))}\n"

    # Handle strategy format from the strategist
    strategy = agent_analysis_dict.get("strategy", {})
    if strategy:
        analysis_content += f"\nMVP Scope: {strategy.get('mvpScope', 'N/A')}\n"
        analysis_content += f"Unfair Advantage: {strategy.get('unfairAdvantage', 'N/A')}\n"
        analysis_content += f"GTM Path: {strategy.get('gtmPath', 'N/A')}\n"

    # Handle legacy startupIdea format
    if "startupIdea" in agent_analysis_dict:
        idea = agent_analysis_dict["startupIdea"]
        analysis_content += f"Name: {idea.get('startupName', 'N/A')}\n"
        analysis_content += f"Pitch: {idea.get('oneLiner', 'N/A')}\n"
        if "targetUser" in idea:
            analysis_content += f"User Persona: {idea['targetUser'].get('persona', 'N/A')}\n"

    kb.insert(
        text_content=analysis_content,
        metadata={
            "user_id": user_id,
            "arxiv_id": paper_arxiv_id,
            "doc_type": "agent_analysis",
            "indexed_at": datetime.utcnow().isoformat()
        }
    )
    
    print(f"Finished indexing vectors to user_knowledge for {paper_arxiv_id}")
