import os
import json
from datetime import datetime

from agno.knowledge.knowledge import Knowledge
from agno.knowledge.embedder.aws_bedrock import AwsBedrockEmbedder
from agno.vectordb.pgvector import PgVector

def get_knowledge_base():
    """Initializes and returns the Knowledge Base connected to Supabase PgVector."""
    # Build complete Postgres connect string out of standard Supabase variables
    db_url = os.environ.get("SUPABASE_DB_URL")
    
    if not db_url:
        print("Warning: SUPABASE_DB_URL not configured. Embeddings will not be saved.")
        return None

    # CRITICAL: Prevent Boto3 from hanging on IMDS metadata timeouts if these are explicitly empty
    os.environ.pop("AWS_ACCESS_KEY_ID", None)
    os.environ.pop("AWS_SECRET_ACCESS_KEY", None)

    # We use Amazon Nova Multimodal Embeddings (amazon.nova-multimodal-embed-v1:0)
    # Note: AWS Bedrock requires AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION
    import boto3
    boto_session = boto3.Session(region_name=os.environ.get("AWS_REGION", "us-east-1"))
    embedder = AwsBedrockEmbedder(
        id="amazon.nova-multimodal-embed-v1:0",
        session=boto_session
        # Default dimensions for multimodal-embed is typically 1024 or 384 depending on config,
        # but Agno relies on the vector data type created by pgvector inside Supabase.
    )

    vector_db = PgVector(
        table_name="user_knowledge", # This triggers Agno to create user_knowledge table
        db_url=db_url,
        embedder=embedder,
    )

    return Knowledge(
        name="User Document and SaaS Knowledge Base",
        description="A database of research papers and SaaS strategies generated by users.",
        vector_db=vector_db,
    )


def index_paper_session(user_id: str, paper_arxiv_id: str, paper_title: str, abstract: str, agent_analysis_dict: dict):
    """
    Takes the parsed SaaS agent results and the raw paper abstract and stores them 
    in the Supabase PgVector database under the specific user's namespace.
    """
    kb = get_knowledge_base()
    if not kb:
        return

    print(f"Indexing session for User {user_id} | Paper: {paper_arxiv_id}...")

    # Document 1: The Raw Abstract 
    abstract_content = f"Title: {paper_title}\nArXiv ID: {paper_arxiv_id}\nAbstract:\n{abstract}"
    kb.insert(
        text_content=abstract_content,
        metadata={
            "user_id": user_id,
            "arxiv_id": paper_arxiv_id,
            "doc_type": "paper_abstract",
            "indexed_at": datetime.utcnow().isoformat()
        }
    )

    # Document 2: The Agent Analysis / Startup Idea
    analysis_content = f"SaaS Strategy derived from {paper_title}:\n\n"
    if "startupIdea" in agent_analysis_dict:
        idea = agent_analysis_dict["startupIdea"]
        analysis_content += f"Name: {idea.get('startupName', 'N/A')}\n"
        analysis_content += f"Pitch: {idea.get('oneLiner', 'N/A')}\n"
        if "targetUser" in idea:
            analysis_content += f"User Persona: {idea['targetUser'].get('persona', 'N/A')}\n"
            analysis_content += f"Pain Point: {idea['targetUser'].get('painPoint', 'N/A')}\n"
        
        if "product" in idea:
            analysis_content += f"Core Feature: {idea['product'].get('coreFeature', 'N/A')}\n"

    # Add SWOT if available
    if "swot" in agent_analysis_dict:
        swot = agent_analysis_dict["swot"]
        analysis_content += f"\nStrengths: {', '.join(swot.get('strengths', []))}"
        analysis_content += f"\nOpportunities: {', '.join(swot.get('opportunities', []))}"

    kb.insert(
        text_content=analysis_content,
        metadata={
            "user_id": user_id,
            "arxiv_id": paper_arxiv_id,
            "doc_type": "agent_analysis",
            "indexed_at": datetime.utcnow().isoformat()
        }
    )
    
    print(f"Finished indexing vectors to user_knowledge for {paper_arxiv_id}")
